### ISSUE TITLE
Day 4 Mastering Framer 

### ISSUE THREAD

**Issue by SikandarJODD** [alisamadiii/Portfolio#8]
Image is Missing - Rabbit Tech 
![image](https://github.com/user-attachments/assets/051fac2f-5ecf-4dfd-aa70-d6e27aa86853)
After Click on eye : 
![image](https://github.com/user-attachments/assets/4fefb108-44e2-4ace-95cb-78bd4a60400c)

**Comment by alisamadiii** [comment]
Thanks, I removed this animation from my portfolio.
